# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCase3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome("/Users/afisher/Downloads/chrome_drivers/98/chromedriver")
  #  self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_case3(self):
    self.driver.get("https://blog.griddynamics.com/")
    self.driver.set_window_size(1440, 790)
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-focused > .ui-button-block").click()
    self.driver.find_element(By.ID, "form-field-input-71").click()
    self.driver.find_element(By.ID, "form-field-input-71").send_keys("Anna")
    self.driver.find_element(By.ID, "form-field-input-73").click()
    self.driver.find_element(By.ID, "form-field-input-73").send_keys("Smith")
    self.driver.find_element(By.ID, "form-field-input-75").click()
    self.driver.execute_script("window.scrollTo(0,240)")
    self.driver.find_element(By.ID, "form-field-input-75").send_keys("annasmith@griddynamics.com")
    self.driver.find_element(By.CSS_SELECTOR, "#form-field-select-83 .ui-select-label-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-select-option:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox-control:nth-child(7) .ui-checkbox-cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-invalid > .ui-checkbox > .ui-checkbox-cell").click()
    self.driver.execute_script("window.scrollTo(0,213)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block").click()
    print(f"selected_text:{selected_text}\n")
    assert selected_text == HomePage.text_find
