# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCase3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome("../chromedriver/chromedriver")

  
  def teardown_method(self, method):

    pass
  
  def test_case3(self):
    self.driver.get("https://blog.griddynamics.com/")
    self.driver.set_window_size(1440, 790)
    element = self.driver.find_element(By.XPATH, "//a[contains(@class,'contact-button')]")
    assert element.is_displayed()
    element.click()

    elementFN  = self.driver.find_element(By.XPATH,"//input[contains(@formcontrolname,'firstName')]")
    assert elementFN.is_displayed()
    elementFN.send_keys("Anna")

    elementLN = self.driver.find_element(By.XPATH, "//input[contains(@formcontrolname,'lastName')]")
    assert elementLN.is_displayed()
    elementLN.send_keys("Smith")

    elementmail = self.driver.find_element(By.XPATH, "//input[contains(@formcontrolname,'email')]")
    assert elementmail.is_displayed()
    elementmail.send_keys("annasmith@griddynamics.com")

    elementPrivacy = self.driver.find_element(By.XPATH,
    "//gd-checkbox[contains(@formcontrolname,'policy')]//label[@class='ui-checkbox']//div[contains(@class,'ui-checkbox-cell')]")

    self.driver.execute_script("arguments[0].click();", elementPrivacy)
    assert elementPrivacy.is_displayed()
    assert elementPrivacy.get_attribute('class') == 'ui-checkbox-cell ui-checkbox-cell-checked'



    elementSubmitButton = self.driver.find_element(By.XPATH,"//button[contains(@type,'submit') and contains(@class,'submit-button')]")
    assert elementSubmitButton.is_displayed()
    assert elementSubmitButton.get_attribute('disabled') == 'true'





    elementGd = self.driver.find_element(By.CSS_SELECTOR, ".ui-select-option:nth-child(4)")
    assert elementGd.is_displayed()
    elementGd.click()

    elementch = self.driver.find_element(By.CSS_SELECTOR, ".checkbox-control:nth-child(7) .ui-checkbox-cell")
    assert elementch.is_displayed()
    elementch.click()

    elementui = self.driver.find_element(By.CSS_SELECTOR, ".ng-invalid > .ui-checkbox > .ui-checkbox-cell")
    assert elementui.is_displayed()
    elementui.click()

    self.driver.execute_script("window.scrollTo(0,213)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    assert element.is_displayed()
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    assert element.is_displayed()
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block").click()
    assert element.is_displayed()
