# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCase3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome("/Users/afisher/Downloads/chrome_drivers/98/chromedriver")
  #  self.vars = {}
  
  def teardown_method(self, method):
    # self.driver.quit()
    pass
  
  def test_case3(self):
    self.driver.get("https://blog.griddynamics.com/")
    self.driver.set_window_size(1440, 790)
    element = self.driver.find_element(By.XPATH, "//a[contains(@class,'contact-button')]")
    assert element.is_displayed()
    element.click()

    elementFN  = self.driver.find_element(By.XPATH,"//input[contains(@formcontrolname,'firstName')]")

    assert elementFN.is_displayed()
    elementFN.send_keys("Anna")

    self.driver.find_element(By.NAME, "lastName").click()
    assert element.is_displayed()
    self.driver.find_element(By.NAME, "lastName").send_keys("Smith")
    self.driver.find_element(By.NAME, "email").click()
    assert element.is_displayed()
    self.driver.execute_script("window.scrollTo(0,240)")
    self.driver.find_element(By.NAME, "email").send_keys("annasmith@griddynamics.com")
    self.driver.find_element(By.CSS_SELECTOR, "#form-field-select-83 .ui-select-label-content").click()
    assert element.is_displayed()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-select-option:nth-child(4)").click()
    assert element.is_displayed()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox-control:nth-child(7) .ui-checkbox-cell").click()
    assert element.is_displayed()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-invalid > .ui-checkbox > .ui-checkbox-cell").click()
    assert element.is_displayed()
    self.driver.execute_script("window.scrollTo(0,213)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    assert element.is_displayed()
    #actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block")
    assert element.is_displayed()
    #actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button > .ui-button-block").click()
    assert element.is_displayed()
