# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By


import logging
LOGGER = logging.getLogger(__name__)

class TestCase2:
    def setup_method(self, method):
        self.driver = webdriver.Chrome("../chromedriver/chromedriver")



    def teardown_method(self, method):
        self.driver.quit()

    def test_case2(self):
        self.driver.get("https://blog.griddynamics.com/")
        self.driver.set_window_size(1440, 790)
        element = self.driver.find_element(By.LINK_TEXT, "Insights")
        assert element.is_displayed()
        element.click()
        # cloud devops in filter
        element_cloud = self.driver.find_element(By.XPATH, "//span[@data-value='cloud-and-devops']")
        self.driver.execute_script("arguments[0].click();", element_cloud)

        element_cloud_count = self.driver.find_elements(By.XPATH,
                    "//section[contains(@class,'cloud-and-devops') and contains(@style,'')]//div[@class='container']//div[contains(@class,'row')]//a[contains(@class,'cardtocheck')]")
        LOGGER.critical(f"List:{len(element_cloud_count)}")
        cloud_postid0 = element_cloud_count[0].get_attribute('data-postid')
        LOGGER.critical(f"Cloud post id0:{cloud_postid0}")
        assert len(element_cloud_count) > 1

        # reset filter
        element_all = self.driver.find_element(By.XPATH, "//span[@data-value='all']")
        self.driver.execute_script("arguments[0].click();", element_all)

        element_all_count = self.driver.find_elements(By.XPATH,
                    "//section[contains(@class,'all') and contains(@style,'')]//div[@class='container']//div[contains(@class,'row')]//a[contains(@class,'cardtocheck')]")
        LOGGER.critical(f"List all:{len(element_all_count)}")

        assert len(element_all_count) > 1
        all_postid0 = element_all_count[0].get_attribute('data-postid')
        LOGGER.critical(f"Cloud post id0:{all_postid0}")

        assert cloud_postid0 != all_postid0
