# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestCase2Insight():
    def setup_method(self, method):
        self.driver = webdriver.Chrome("/Users/afisher/Downloads/chrome_drivers/98/chromedriver")

    def teardown_method(self, method):
        self.driver.quit()

    def test_testCase2Insight(self):
        self.driver.get("https://blog.griddynamics.com/")
        self.driver.set_window_size(1440, 790)
        self.driver.execute_script("window.scrollTo(0,473.5)")
        self.driver.find_element(By.LINK_TEXT, "Insights").click()
        # self.driver.find_element(By.LINK_TEXT, "Articles").click()
        self.driver.find_element(By.CSS_SELECTOR, "#topiclist .selected").click()
        self.driver.find_element(By.CSS_SELECTOR, "div > span:nth-child(6)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#topiclist .selected").click()
        self.driver.find_element(By.CSS_SELECTOR, "#topiclist > div").click()
        self.driver.find_element(By.CSS_SELECTOR, "#topiclist .selected").click()
        self.driver.find_element(By.CSS_SELECTOR, "#topiclist .showall").click()

